name: Build test image
on:
  push:
    branches:
      - master
jobs:
  build-and-publish-image:
    name: "Build and publish image to GitHub Container Registry"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . --tag ghcr.io/voneiden/ftsearch:latest
      - name: Push image
        run: docker push ghcr.io/voneiden/ftsearch:latest